# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArchtypeManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import subprocess
import shutil
import json
import zipfile
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QDir
from PyQt5.QtGui import QColor, QFont
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from xmlpreview import XmlAnimationPreview 
from theme_manager import ThemeManager
from counterpreview import CounterPreview
from completeBuild import CompleteBuild
from functools import partial
from typing import Dict
from PIL import Image


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 788)
        self.assets_dir = "./Archetype/theme/assets"
        self.archetype_root="./Archetype"
        self.custom_login = "./CustomThemes"
        self.custom_counter = "./CustomCounters"    
        self.previewimages = "./Preview"
        self.pokeballIcon = "./Archetype/theme/assets/jaejGI7pIp/res/custom/counter"
        self.gamePath = ""
        self.themeFolder = "./Archetype/theme"
        self.configPath="./config.json"
        self.defaultConfig="./default.json"
        self.modsLocation="./Mods"
        self.flipped_cache = {}
        self.theme_manager = ThemeManager()

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        central_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1116, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.LoginScreen = QtWidgets.QWidget()
        self.LoginScreen.setObjectName("LoginScreen")
        self.unovaLoginOptions = QtWidgets.QFrame(self.LoginScreen)
        self.unovaLoginOptions.setGeometry(QtCore.QRect(5, 415, 340, 261))
        self.unovaLoginOptions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.unovaLoginOptions.setObjectName("unovaLoginOptions")
        self.label_8 = self.make_label(self.unovaLoginOptions,"label_8",12,False,(20,65,181,201),None)
        self.label_9 = self.make_label(self.unovaLoginOptions,"label_9",16,True,(15,15,311,41),None)
        self.zekromColor = KColorButton(self.unovaLoginOptions)
        self.zekromColor.setGeometry(QtCore.QRect(150, 175, 48, 23))
        self.zekromColor.setObjectName("zekrom-color")
        self.reshiramColor = KColorButton(self.unovaLoginOptions)
        self.reshiramColor.setGeometry(QtCore.QRect(150, 90, 48, 23))
        self.reshiramColor.setObjectName("reshiram-color")
        self.zekromAura = KColorButton(self.unovaLoginOptions)
        self.zekromAura.setGeometry(QtCore.QRect(150, 220, 48, 23))
        self.zekromAura.setObjectName("zekrom-aura")
        self.reshiramAura = KColorButton(self.unovaLoginOptions)
        self.reshiramAura.setGeometry(QtCore.QRect(150, 130, 48, 25))
        self.reshiramAura.setObjectName("reshiram-aura")
        self.addOwnLogin = QtWidgets.QFrame(self.LoginScreen)
        self.addOwnLogin.setGeometry(QtCore.QRect(5, 15, 436, 66))
        self.addOwnLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addOwnLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addOwnLogin.setObjectName("addOwnLogin")
        self.label_2 = self.make_label(self.addOwnLogin,"label_2",12,True,(-5,15,241,30),None)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2_status = QtWidgets.QLabel(self.LoginScreen)
        self.label_2_status.setGeometry(QtCore.QRect(25, 55, 400, 20))
        self.label_2_status.setText("")  # start empty
        self.label_2_status.setStyleSheet("color: green; font-size: 9pt;")
        ##Login Selector        
        self.loginBrowse = QtWidgets.QPushButton(self.addOwnLogin)
        self.loginBrowse.setGeometry(QtCore.QRect(235, 20, 80, 25))
        self.loginBrowse.setObjectName("loginBrowse")
        self.loginBrowse.clicked.connect(self.handle_login_browse)        
        self.chooseLogin = QtWidgets.QFrame(self.LoginScreen)
        self.chooseLogin.setGeometry(QtCore.QRect(5, 90, 340, 320))
        self.chooseLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chooseLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chooseLogin.setObjectName("chooseLogin")
        self.loginDrop = QtWidgets.QComboBox(self.chooseLogin)
        self.loginDrop.setGeometry(QtCore.QRect(15, 35, 301, 25))
        self.loginDrop.setObjectName("loginDrop")

        self.label = self.make_label(self.chooseLogin,"label",16,True,(60,-10,226,51),None)
        self.loginPreviewFrame = QtWidgets.QFrame(self.LoginScreen)
        self.loginPreviewFrame.setGeometry(QtCore.QRect(360, 170, 731, 506))
        self.loginPreviewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginPreviewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginPreviewFrame.setObjectName("loginPreviewFrame")
        default_xml = os.path.join(self.assets_dir, "Allstars.xml")
        self.loginPreview = XmlAnimationPreview(default_xml,parent=self.loginPreviewFrame)
        self.loginPreview.setGeometry(QtCore.QRect(5, 5, 721, 496))
        self.loginPreview.setObjectName("loginPreview")
        self.tabWidget.addTab(self.LoginScreen, "")
        self.EncounterCounter = QtWidgets.QWidget()
        self.EncounterCounter.setObjectName("EncounterCounter")
        self.counterColorFrame = QtWidgets.QFrame(self.EncounterCounter)
        self.counterColorFrame.setGeometry(QtCore.QRect(15, 105, 306, 391))
        self.counterColorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.counterColorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.counterColorFrame.setObjectName("counterColorFrame")
        self.ballColor = KColorButton(self.counterColorFrame)
        self.ballColor.setGeometry(QtCore.QRect(220, 75, 48, 23))
        self.ballColor.setObjectName("counter-ball-color")
        self.mainColor = KColorButton(self.counterColorFrame)
        self.mainColor.setGeometry(QtCore.QRect(220, 205, 48, 23))
        self.mainColor.setObjectName("counter-main-color")
        self.fontColor = KColorButton(self.counterColorFrame)
        self.fontColor.setGeometry(QtCore.QRect(220, 290, 48, 23))
        self.fontColor.setObjectName("counter-font-color")
        self.label_6 = self.make_label(self.counterColorFrame,"label_6",16,True,(15,15,311,41),None)       
        self.minMaxButtonColor = KColorButton(self.counterColorFrame)
        self.minMaxButtonColor.setGeometry(QtCore.QRect(220, 160, 48, 23))
        self.minMaxButtonColor.setObjectName("counter-min-max-button-color")
        self.ballOutline = KColorButton(self.counterColorFrame)
        self.ballOutline.setGeometry(QtCore.QRect(220, 115, 48, 25))
        self.ballOutline.setObjectName("ballOutline")
        self.subColor = KColorButton(self.counterColorFrame)
        self.subColor.setGeometry(QtCore.QRect(220, 250, 48, 23))
        self.subColor.setObjectName("counter-sub-color")
        self.label_7 = self.make_label(self.counterColorFrame,"label_7",12,False,(20,35,181,361),None)
        self.fontBorder = KColorButton(self.counterColorFrame)
        self.fontBorder.setGeometry(QtCore.QRect(220, 335, 48, 23))
        self.fontBorder.setObjectName("counter-font-border")
        self.counterSelectorFrame = QtWidgets.QFrame(self.EncounterCounter)
        self.counterSelectorFrame.setGeometry(QtCore.QRect(15, 20, 531, 80))
        self.counterSelectorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.counterSelectorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.counterSelectorFrame.setObjectName("counterSelectorFrame")
        ##CounterDrop        
        self.counterDrop = QtWidgets.QComboBox(self.counterSelectorFrame)
        self.counterDrop.setGeometry(QtCore.QRect(225, 25, 301, 25))
        self.counterDrop.setObjectName("counterDrop")
        self.counterDrop.setCurrentIndex(1)

        self.label_5 = self.make_label(self.counterSelectorFrame,"label_5",16,True,(5,5,211,61),None)

        self.counterPreviewFrame = QtWidgets.QFrame(self.EncounterCounter)
        self.counterPreviewFrame.setGeometry(QtCore.QRect(345, 125, 731, 506))
        self.counterPreviewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.counterPreviewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.counterPreviewFrame.setObjectName("counterPreviewFrame")
        ##Counter Preview
        default_xml = os.path.join(self.assets_dir, "Counter-Right.xml")
        self.counterPreview = CounterPreview(parent=self.counterPreviewFrame)
        self.counterPreview.setGeometry(QtCore.QRect(5, 5, 721, 496))
        self.counterPreview.setObjectName("counterPreview")

        self.counterText = QtWidgets.QLabel(self.counterPreviewFrame)
        self.counterText.setGeometry(QtCore.QRect(300, 170, 211, 200))
        font = QFont("Noto Sans", 14)
        font.setBold(True)
        self.counterText.setFont(font)
        self.counterText.setObjectName("counterText")
        self.fontColor.colorChanged.connect(lambda color: self.updateFontColor(color, self.counterText))

 
        self.addOwnVaritou = QtWidgets.QFrame(self.EncounterCounter)
        self.addOwnVaritou.setGeometry(QtCore.QRect(565, 20, 456, 86))
        self.addOwnVaritou.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.addOwnVaritou.setObjectName("addOwnVaritou")
        self.label_3 = self.make_label(self.addOwnVaritou,"label_3",12,True,(25,0,211,30),None)

        self.varitouBrowse = QtWidgets.QPushButton(self.addOwnVaritou)
        self.varitouBrowse.setGeometry(QtCore.QRect(235, 5, 80, 25))
        self.varitouBrowse.setObjectName("varitouBrowse")
        self.varitouBrowse.clicked.connect(self.handle_vartiou_browse)        
        
        self.label_16 = self.make_label(self.addOwnVaritou,"label_16",9,False,(25,35,386,17),None)

        self.customDrop = QtWidgets.QComboBox(self.addOwnVaritou)
        self.customDrop.setGeometry(QtCore.QRect(150, 55, 301, 25))
        self.customDrop.setObjectName("customDrop")

        self.label_18 = self.make_label(self.addOwnVaritou,"label_18",12,True,(5,50,141,30),None)

        self.tabWidget.addTab(self.EncounterCounter, "")
        self.WindowColors = QtWidgets.QWidget()
        self.WindowColors.setObjectName("WindowColors")
        self.windowPreviewFrame = QtWidgets.QFrame(self.WindowColors)
        self.windowPreviewFrame.setGeometry(QtCore.QRect(15, 25, 829, 653))
        self.windowPreviewFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.windowPreviewFrame.setObjectName("windowPreviewFrame")
        self.windowPreview = CounterPreview(parent=self.windowPreviewFrame)
        self.windowPreview.setGeometry(QtCore.QRect(5, 5, 805, 577))
        self.windowPreview.setObjectName("windowPreview")

        self.hpBar = CounterPreview(parent=self.windowPreviewFrame)
        self.hpBar.setGeometry(QtCore.QRect(7, 592, 297, 63))
        self.hpBar.setObjectName("hpBar")
        
        self.BerryPreview = QtWidgets.QWidget(self.windowPreviewFrame)
        self.BerryPreview.setGeometry(QtCore.QRect(347, 592, 307, 57))
        self.BerryPreview.setObjectName("BerryPreview")
        self.MainWindowFrame = QtWidgets.QFrame(self.WindowColors)
        self.MainWindowFrame.setGeometry(QtCore.QRect(868, 10, 233, 656))
        self.MainWindowFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MainWindowFrame.setObjectName("MainWindowFrame")
        self.accentColorW = KColorButton(self.MainWindowFrame)
        self.accentColorW.setGeometry(QtCore.QRect(158, 152, 48, 23))
        self.accentColorW.setObjectName("accent-color")
        self.subColorW = KColorButton(self.MainWindowFrame)
        self.subColorW.setGeometry(QtCore.QRect(158, 94, 48, 25))
        self.subColorW.setObjectName("sub-color")
        self.mainColorW = KColorButton(self.MainWindowFrame)
        self.mainColorW.setGeometry(QtCore.QRect(158, 66, 48, 23))
        self.mainColorW.setObjectName("main-color")

        self.label_11 = self.make_label(self.MainWindowFrame,"label_11",16,False,(8,171,101,146),None)

        self.fontButtonW = KColorButton(self.MainWindowFrame)
        self.fontButtonW.setGeometry(QtCore.QRect(158, 378, 48, 23))
        self.fontButtonW.setObjectName("font-button-color")

        self.label_10 = self.make_label(self.MainWindowFrame,"label_10",16,False,(8,56,81,121),None)
        self.label_4 = self.make_label(self.MainWindowFrame,"label_4",16,False,(8,319,146,137),None)

        self.buttonColorW = KColorButton(self.MainWindowFrame)
        self.buttonColorW.setGeometry(QtCore.QRect(158, 124, 48, 23))
        self.buttonColorW.setObjectName("button-color")
        self.fontSubW = KColorButton(self.MainWindowFrame)
        self.fontSubW.setGeometry(QtCore.QRect(158, 348, 48, 25))
        self.fontSubW.setObjectName("font-sub-color")
        self.fontDisabledColorW = KColorButton(self.MainWindowFrame)
        self.fontDisabledColorW.setGeometry(QtCore.QRect(158, 406, 48, 23))
        self.fontDisabledColorW.setObjectName("font-disabled-color")
        self.xpColorW = KColorButton(self.MainWindowFrame)
        self.xpColorW.setGeometry(QtCore.QRect(158, 264, 48, 23))
        self.xpColorW.setObjectName("xp-color")
        self.friendshipColorW = KColorButton(self.MainWindowFrame)
        self.friendshipColorW.setGeometry(QtCore.QRect(158, 292, 48, 23))
        self.friendshipColorW.setObjectName("friendship-color")
        self.fontMainW = KColorButton(self.MainWindowFrame)
        self.fontMainW.setGeometry(QtCore.QRect(158, 320, 48, 23))
        self.fontMainW.setObjectName("font-main-color")
        self.hpHighW = KColorButton(self.MainWindowFrame)
        self.hpHighW.setGeometry(QtCore.QRect(158, 179, 48, 23))
        self.hpHighW.setObjectName("hp-high-color")
        self.hpLowW = KColorButton(self.MainWindowFrame)
        self.hpLowW.setGeometry(QtCore.QRect(158, 234, 48, 25))
        self.hpLowW.setObjectName("hp-low-color")
        self.hpMidW = KColorButton(self.MainWindowFrame)
        self.hpMidW.setGeometry(QtCore.QRect(158, 206, 48, 23))
        self.hpMidW.setObjectName("hp-mid-color")

        self.label_13 = self.make_label(self.MainWindowFrame,"label_13",16,True,(46,1,155,61),None)
        
        self.waterW = KColorButton(self.MainWindowFrame)
        self.waterW.setGeometry(QtCore.QRect(158, 546, 48, 25))
        self.waterW.setObjectName("water-warning")

        self.label_14 = self.make_label(self.MainWindowFrame,"label_14",16,True,(-2,464,230,61),None)

        self.waterbg = KColorButton(self.MainWindowFrame)
        self.waterbg.setGeometry(QtCore.QRect(158, 518, 48, 23))
        self.waterbg.setObjectName("water-background")
        self.berryProgress = KColorButton(self.MainWindowFrame)
        self.berryProgress.setGeometry(QtCore.QRect(158, 576, 48, 23))
        self.berryProgress.setObjectName("berry-progress")

        self.label_12 = self.make_label(self.MainWindowFrame,"label_12",16,False,(8,515,143,139),None)

        self.berryWarning = KColorButton(self.MainWindowFrame)
        self.berryWarning.setGeometry(QtCore.QRect(158, 604, 48, 23))
        self.berryWarning.setObjectName("berry-progress-warning")

        self.berryDisabled = KColorButton(self.MainWindowFrame)
        self.berryDisabled.setGeometry(QtCore.QRect(158, 632, 48, 23))
        self.berryDisabled.setObjectName("berry-progress-disabled")

        self.iconColorW = KColorButton(self.MainWindowFrame)
        self.iconColorW.setGeometry(QtCore.QRect(158, 434, 48, 23))
        self.iconColorW.setObjectName("icon-color")

        ##Window Preview Fonts###
        self.windowTextFontMain = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontMain.setGeometry(QtCore.QRect(40, -50, 211, 200))
        font = QFont("Noto Sans", 8)
        font.setBold(True)
        self.windowTextFontMain.setFont(font)
        self.windowTextFontMain.setObjectName("windowMainText")
        self.fontMainW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontMain))
        self.windowTextFontMain2 = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontMain2.setGeometry(QtCore.QRect(47, -27, 211, 200))
        font = QFont("Noto Sans", 7)
        self.windowTextFontMain2.setFont(font)
        self.windowTextFontMain2.setObjectName("windowMainText2")
        self.fontMainW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontMain2))


        self.windowTextFontSub = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontSub.setGeometry(QtCore.QRect(232, 147, 717, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontSub.setFont(font)
        self.windowTextFontSub.setObjectName("windowSubText")
        self.fontSubW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontSub))     
        self.windowTextFontSub2 = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontSub2.setGeometry(QtCore.QRect(110, 115, 717, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontSub2.setFont(font)
        self.windowTextFontSub2.setObjectName("windowSubText2")
        self.fontSubW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontSub2))    

        ##Min Max IV Static Colors##
        self.windowTextFontMinIV = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontMinIV.setGeometry(QtCore.QRect(428, 147, 61, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontMinIV.setFont(font)
        self.windowTextFontMinIV.setObjectName("WindowMinIV")
        self.windowTextFontMinIV.setStyleSheet("color: #f46263;")
        self.windowTextFontMaxIV = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontMaxIV.setGeometry(QtCore.QRect(317, 147, 61, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontMaxIV.setFont(font)
        self.windowTextFontMaxIV.setObjectName("WindowMaxIV")
        self.windowTextFontMaxIV.setStyleSheet("color: #6eb66e;") 
        
        ##Button Font##
        self.windowTextFontButton1 = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontButton1.setGeometry(QtCore.QRect(160,45, 717, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontButton1.setFont(font)
        self.windowTextFontButton1.setObjectName("TextFontButton1")
        self.fontButtonW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontButton1))     
        self.windowTextFontButton2 = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontButton2.setGeometry(QtCore.QRect(100, 80, 717, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontButton2.setFont(font)
        self.windowTextFontButton2.setObjectName("TextFontButton2")
        self.fontButtonW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontButton2))    
        self.windowTextFontButton3 = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontButton3.setGeometry(QtCore.QRect(130, 147, 717, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontButton3.setFont(font)
        self.windowTextFontButton3.setObjectName("TextFontButton3")
        self.fontButtonW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontButton3))    
        self.windowTextFontButton4 = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontButton4.setGeometry(QtCore.QRect(225, 493, 717, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontButton4.setFont(font)
        self.windowTextFontButton4.setObjectName("TextFontButton4")
        self.fontButtonW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontButton4))    
        
        ##Font Disabled##
        self.windowTextFontDisabled1 = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontDisabled1.setGeometry(QtCore.QRect(602, 80, 61, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontDisabled1.setFont(font)
        self.windowTextFontDisabled1.setObjectName("TextFontDisabled1")
        self.fontDisabledColorW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontDisabled1))  
        self.windowTextFontDisabled2 = QtWidgets.QLabel(self.windowPreviewFrame)
        self.windowTextFontDisabled2.setGeometry(QtCore.QRect(160, 493, 100, 61))
        font = QFont("Noto Sans", 8)
        self.windowTextFontDisabled2.setFont(font)
        self.windowTextFontDisabled2.setObjectName("TextFontDisabled1")
        self.fontDisabledColorW.colorChanged.connect(lambda color: self.updateFontColor(color, self.windowTextFontDisabled2))  

        self.label_12.raise_()
        self.label_11.raise_()
        self.label_4.raise_()
        self.label_10.raise_()
        self.accentColorW.raise_()
        self.subColorW.raise_()
        self.mainColorW.raise_()
        self.fontButtonW.raise_()
        self.buttonColorW.raise_()
        self.fontSubW.raise_()
        self.fontDisabledColorW.raise_()
        self.xpColorW.raise_()
        self.friendshipColorW.raise_()
        self.fontMainW.raise_()
        self.hpHighW.raise_()
        self.hpLowW.raise_()
        self.hpMidW.raise_()
        self.label_13.raise_()
        self.waterW.raise_()
        self.label_14.raise_()
        self.waterbg.raise_()
        self.berryProgress.raise_()
        self.berryWarning.raise_()
        self.tabWidget.addTab(self.WindowColors, "")
        self.OtherScreen = QtWidgets.QWidget()
        self.OtherScreen.setObjectName("OtherScreen")
        self.cursoFrame = QtWidgets.QFrame(self.OtherScreen)
        self.cursoFrame.setGeometry(QtCore.QRect(10, 30, 561, 121))
        self.cursoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cursoFrame.setObjectName("cursoFrame")
        self.cursorDrop = QtWidgets.QComboBox(self.cursoFrame)
        self.cursorDrop.setGeometry(QtCore.QRect(225, 25, 301, 25))
        self.cursorDrop.setObjectName("cursorDrop")

        self.label_15 = self.make_label(self.cursoFrame,"label_15",16,True,(5,5,211,61),None)

        self.cursorBrowse = QtWidgets.QPushButton(self.cursoFrame)
        self.cursorBrowse.setGeometry(QtCore.QRect(435, 70, 80, 25))
        self.cursorBrowse.setObjectName("cursorBrowse")
       
        self.label_17 = self.make_label(self.cursoFrame,"label_17",12,True,(195,65,241,30),None)

        self.cursorPreviewFrame = QtWidgets.QFrame(self.OtherScreen)
        self.cursorPreviewFrame.setGeometry(QtCore.QRect(680, 10, 321, 166))
        self.cursorPreviewFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cursorPreviewFrame.setObjectName("cursorPreviewFrame")
        self.cursorPreview = QtWidgets.QWidget(self.cursorPreviewFrame)
        self.cursorPreview.setGeometry(QtCore.QRect(5, 5, 310, 155))
        self.cursorPreview.setObjectName("cursorPreview")
        self.iconFrame = QtWidgets.QFrame(self.OtherScreen)
        self.iconFrame.setGeometry(QtCore.QRect(10, 225, 561, 80))
        self.iconFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.iconFrame.setObjectName("iconFrame")
        self.iconDrop = QtWidgets.QComboBox(self.iconFrame)
        self.iconDrop.setGeometry(QtCore.QRect(225, 25, 301, 25))
        self.iconDrop.setObjectName("iconDrop")
        self.iconDrop.addItem("")
        self.iconDrop.addItem("")

        self.label_20 = self.make_label(self.iconFrame,"label_20",16,True,(5,5,211,61),None)

        self.speechBubblesFrame = QtWidgets.QFrame(self.OtherScreen)
        self.speechBubblesFrame.setGeometry(QtCore.QRect(10, 385, 561, 121))
        self.speechBubblesFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.speechBubblesFrame.setObjectName("speechBubblesFrame")
        self.speechDrop = QtWidgets.QComboBox(self.speechBubblesFrame)
        self.speechDrop.setGeometry(QtCore.QRect(225, 25, 301, 25))
        self.speechDrop.setObjectName("speechDrop")

        self.label_23 = self.make_label(self.speechBubblesFrame,"label_23",16,True,(5,5,211,61),None)

        self.speechBrowse = QtWidgets.QPushButton(self.speechBubblesFrame)
        self.speechBrowse.setGeometry(QtCore.QRect(435, 70, 80, 25))
        self.speechBrowse.setObjectName("speechBrowse")

        self.label_24 = self.make_label(self.speechBubblesFrame,"label_24",12,True,(195,65,241,30),None)

        self.speechBubblePreviewFrame = QtWidgets.QFrame(self.OtherScreen)
        self.speechBubblePreviewFrame.setGeometry(QtCore.QRect(680, 365, 321, 166))
        self.speechBubblePreviewFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.speechBubblePreviewFrame.setObjectName("speechBubblePreviewFrame")
        self.speechBubblePreview = QtWidgets.QWidget(self.speechBubblePreviewFrame)
        self.speechBubblePreview.setGeometry(QtCore.QRect(5, 5, 310, 155))
        self.speechBubblePreview.setObjectName("speechBubblePreview")
        self.tabWidget.addTab(self.OtherScreen, "")
        self.Archetype = QtWidgets.QWidget()
        self.Archetype.setObjectName("Archetype")
        self.Mods = QtWidgets.QWidget()
        self.Mods.setObjectName("Mods")
        self.GetArchtype = QtWidgets.QFrame(self.Archetype)
        self.GetArchtype.setGeometry(QtCore.QRect(40, 80, 1011, 596))
        self.GetArchtype.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.GetArchtype.setObjectName("GetArchtype")

        self.label_25 = self.make_label(self.GetArchtype,"label_25",16,True,(5,5,236,61),None)

        self.downloadArch = QtWidgets.QPushButton(self.GetArchtype)
        self.downloadArch.setGeometry(QtCore.QRect(245, 15, 281, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.downloadArch.setFont(font)
        self.downloadArch.setObjectName("downloadArch")

        self.labelBrowse = self.make_label(self.GetArchtype,"Set Game Path",16,True,(5,70,210,61),None)

        self.setGamePath = QtWidgets.QPushButton(self.GetArchtype)
        self.setGamePath.setGeometry(QtCore.QRect(245, 80, 280, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.setGamePath.setFont(font)
        self.setGamePath.setObjectName("setGamePath")
        # self.loadConfig = QtWidgets.QPushButton(self.GetArchtype)
        # self.loadConfig.setGeometry(QtCore.QRect(245, 140, 280, 46))
        # font = QtGui.QFont()
        # font.setPointSize(16)
        # font.setBold(True)
        # font.setWeight(75)
        # self.loadConfig.setFont(font)
        # self.loadConfig.setObjectName("loadConfig")

        # self.label_27 = self.make_label(self.GetArchtype,"label_27",16,True,(5,130,210,61),None)

        self.completeMod = QtWidgets.QPushButton(self.GetArchtype)
        self.completeMod.setGeometry(QtCore.QRect(595, 70, 280, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.completeMod.setFont(font)
        self.completeMod.setObjectName("completeMod")

        self.label_28 = self.make_label(self.GetArchtype,"label_28",16,True,(590,0,306,61),None)

        self.tabWidget.addTab(self.Mods, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.tabWidget.addTab(self.Archetype, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionLoadDefault = QtWidgets.QAction(MainWindow)
        self.actionLoadDefault.setObjectName("actionLoadDefault")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionLoadDefault)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.status_label_archetype = QtWidgets.QLabel(self.GetArchtype)
        self.status_label_archetype.setGeometry(QtCore.QRect(72, 358, 537, 143))
        self.status_label_archetype.setText("")  # start empty
        self.status_label_archetype.setStyleSheet("color: green; font-size: 18pt;")

        self.status_label_custom_counter = QtWidgets.QLabel(self.counterPreview)
        self.status_label_custom_counter.setGeometry(QtCore.QRect(277, 10, 383, 17))
        self.status_label_custom_counter.setText("")  # start empty
        self.status_label_custom_counter.setStyleSheet("color: green; font-size: 8pt;")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        default_colors = {
            self.mainColorW: "#42b9ff",
            self.subColorW: "#1c2328",
            self.buttonColorW: "#263238",
            self.accentColorW: "#2d3b40",
            self.hpHighW: "#82e026",
            self.hpLowW: "#dc2222",
            self.hpMidW: "#ecd031",
            self.xpColorW: "#2eb2f8",
            self.friendshipColorW: "#b61ae8",
            self.fontMainW: "#ffffff",
            self.fontSubW: "#acb7b9",
            self.fontButtonW: "#84959b",
            self.fontDisabledColorW: "#9984959b",
            self.waterbg: "#D91c2328",
            self.waterW: "#dc2222",
            self.berryProgress: "#42b9ff",
            self.berryWarning: "#42b9ff",
            self.iconColorW: "#ffffff",
            self.ballColor: "#42b9ff",
            self.mainColor: "#1c2328",
            self.subColor:"#42b9ff",
            self.minMaxButtonColor:"#ffffff",
        }
        for widget, color in default_colors.items():
            widget.setColor(color)
        self.reshiramAura.setColor(QColor("#cb4e03"))
        self.reshiramColor.setColor(QColor("#1b2526"))
        self.zekromAura.setColor(QColor("#00a5c9"))
        self.zekromColor.setColor(QColor("#070b0b"))

        ##defs##
        self.setup_color_hooks() 
        self.update_login_drop()
        self.update_counter_drop()
        self.update_vartiou_drop()
        self.update_counter_preview()   
        self.update_login_preview()
        self.update_window_preview()
        self.update_hp_preview()
        self.update_bubbles_drop()
        self.update_icon_drop()
        self.update_cursor_drop()

        ##Drops##
        self.loginDrop.currentIndexChanged.connect(self.update_login_preview)
        self.counterDrop.currentIndexChanged.connect(self.update_counter_preview)
        self.customDrop.currentIndexChanged.connect(self.update_vartiou_drop)

        ##Counter Colors##
        self.mainColor.colorChanged.connect(lambda c: self.counterPreview.set_layer_tint(0, QColor(c)))
        self.subColor.colorChanged.connect(lambda c: self.counterPreview.set_layer_tint(1, QColor(c)))
        self.minMaxButtonColor.colorChanged.connect(lambda c: self.counterPreview.set_layer_tint(2, QColor(c)))
        self.ballOutline.colorChanged.connect(lambda c: self.counterPreview.set_layer_tint(8, c))
        self.ballColor.colorChanged.connect(lambda c: self.counterPreview.set_layer_tint(7, c))

        ##Window Colors##``
        self.buttonColorW.colorChanged.connect(lambda c:self.windowPreview.set_layer_tint(0, QColor(c)))
        self.iconColorW.colorChanged.connect(lambda c: self.windowPreview.set_layer_tint(1, QColor(c)))
        self.subColorW.colorChanged.connect(lambda c: self.windowPreview.set_layer_tint(3, QColor(c)))
        self.accentColorW.colorChanged.connect(lambda c: self.windowPreview.set_layer_tint(4, QColor(c)))
        self.mainColorW.colorChanged.connect(lambda c: self.windowPreview.set_layer_tint(5, QColor(c)))
        
        ##HP Bars##
        self.subColorW.colorChanged.connect(lambda c:self.hpBar.set_layer_tint(1, QColor(c)))
        self.hpHighW.colorChanged.connect(lambda c: self.hpBar.set_layer_tint(3, QColor(c)))
        self.hpMidW.colorChanged.connect(lambda c: self.hpBar.set_layer_tint(4, QColor(c)))
        self.hpLowW.colorChanged.connect(lambda c: self.hpBar.set_layer_tint(5, QColor(c)))
        self.xpColorW.colorChanged.connect(lambda c: self.hpBar.set_layer_tint(6, QColor(c)))

        ##Berry Preview##
        #TO-DO

        self.downloadArch.clicked.connect(self.downloadLatestArch)
        self.setGamePath.clicked.connect(self.select_file_path)
        self.actionSave.triggered.connect(self.save_config)
        self.actionSaveAs.triggered.connect(self.save_config_as)
        self.actionLoad.triggered.connect(self.load_config)
        self.actionLoadDefault.triggered.connect(self.load_default_config)
        self.actionExit.triggered.connect(MainWindow.close)
        # self.loadConfig.clicked.connect(self.load_default_config)
        self.setGamePath.clicked.connect(self.select_file_path)
        self.completeMod.clicked.connect(self.complete_build)
        ##Text Colors##
        self.colorLinkedLabels = [
        self.counterText,
        self.windowTextFontMain,
        self.windowTextFontMain2,
        self.windowTextFontSub,
        self.windowTextFontButton1,
        self.windowTextFontButton2,
        self.windowTextFontButton3,
        ]
        
        self.status_label_archetype2 = self.make_label(self.GetArchtype,f"<b>Pokemmo Location:</b> {self.get_current_path(self.gamePath)}<br><b>Archetype Status:</b> {self.get_Archstatus()}<br><b>ModCount:</b> {self.mod_count(self.modsLocation)}",16,False,(56,148,819,143),None)
        self.status_label_archetype2.setTextFormat(QtCore.Qt.RichText)
        self.load_last_config()

    def populate_dropdown(
        self,
        combo, 
        base_folder, 
        custom_folder=None, 
        file_ext=None, 
        include_subfolders=True, 
        file_filter=None, 
        exclude_names=None):

        combo.blockSignals(True)
        combo.clear()

        folders = [base_folder]
        if custom_folder and os.path.exists(custom_folder):
            if include_subfolders:
                for subfolder in sorted(os.listdir(custom_folder)):
                    full_path = os.path.join(custom_folder, subfolder)
                    if os.path.isdir(full_path):
                        folders.append(full_path)
            folders.append(custom_folder)

        for folder in folders:
            if not os.path.exists(folder):
                continue

            for file_name in sorted(os.listdir(folder)):
                full_path = os.path.join(folder, file_name)

                # --- folder-only mode (no extension) ---
                if not file_ext and os.path.isdir(full_path):
                    combo.addItem(file_name, full_path)
                    continue

                # --- file mode ---
                if file_ext and not file_name.lower().endswith(file_ext.lower()):
                    continue

                if exclude_names and file_name in exclude_names:
                    continue

                if file_filter and not file_filter(file_name):
                    continue

                display_name = file_name
                if custom_folder and folder.startswith(custom_folder):
                    display_name = file_name

                combo.addItem(display_name, full_path)

        combo.blockSignals(False)

    def update_login_drop(self):
        self.populate_dropdown(
        combo=self.loginDrop,
        base_folder=self.assets_dir,
        custom_folder=self.custom_login,
        file_ext=".xml",
        file_filter=lambda f: not (
            f.startswith(("Counter-", "Cursors-", "Default")) or
            f in ["Round.xml", "Sharp.xml", "Archetype.xml"]
        ),)

    def mod_count(self,path: str)->int:
        if not os.path.isdir(path):
            return 0
        file_count = sum(1 for f in os.listdir(path) if os.path.isfile(os.path.join(path, f)))
        return file_count

    def update_counter_drop(self):
        self.populate_dropdown(
            combo=self.counterDrop,
            base_folder=self.assets_dir,
            custom_folder=self.custom_counter,
            file_ext=".xml",
            file_filter=lambda f: f.startswith("Counter-"),
        )

    def update_vartiou_drop(self):

        self.populate_dropdown(
            combo=self.customDrop,
            base_folder=self.custom_counter,
            file_ext=None,  # folders only
            include_subfolders=False
        ) 
         
    def update_cursor_drop(self):

        self.populate_dropdown(
            combo=self.cursorDrop,
            base_folder=self.assets_dir,
            file_ext=".xml",  # folders only
            include_subfolders=False,
            file_filter=lambda f: f.startswith("Cursors-"),
        )  

    def update_bubbles_drop(self):

        self.populate_dropdown(
            combo=self.speechDrop,
            base_folder=self.assets_dir,
            file_ext=".xml",  # folders only
            include_subfolders=False,
            file_filter=lambda f: f.startswith("Default-"),
        )  

    def update_icon_drop(self):

        self.populate_dropdown(
            combo=self.iconDrop,
            base_folder=self.assets_dir,
            file_ext=".xml",  # folders only
            include_subfolders=False,
            file_filter=lambda f: f.startswith("Sharp") or f.startswith("Round"),
        )  

    def update_login_preview(self):
        # Get the full path stored in the dropdown's item data
        xml_path = self.loginDrop.currentData()
        if xml_path and os.path.exists(xml_path):
            self.loginPreview.set_xml_path(xml_path)
  
    def update_preview_layers(self, preview_widget, base_path, image_list, color_map, combine_map=None):
        if not base_path or not os.path.exists(base_path):
            print(f"[MainWindow] Invalid base path: {base_path}")
            return

        layer_paths = [os.path.join(base_path, img) for img in image_list]
        preview_widget.layer_paths = [p if os.path.exists(p) else None for p in layer_paths]

        # Expand tints to correct size
        while len(preview_widget.layer_tints) < len(layer_paths):
            preview_widget.layer_tints.append(QColor(255, 255, 255, 255))

        # Apply individual colors
        for idx, color_btn in color_map.items():
            preview_widget.layer_tints[idx] = color_btn.color()

        # Handle combined colors (dict: index -> (colorBtn1, colorBtn2))
        if combine_map:
            for idx, (c1, c2) in combine_map.items():
                preview_widget.layer_tints[idx] = self.combine_colors(c1.color(), c2.color())

        preview_widget.update_preview()

    def update_counter_preview(self):
        text = self.counterDrop.currentText()
        layer = [
            "maincolorR.png", "sidecolorR.png",
            "MinMax.png", *["Blank1.png"] * 4,
            os.path.relpath(os.path.join(self.pokeballIcon, "Pokeball-Icon2.png"), self.previewimages),
            os.path.relpath(os.path.join(self.pokeballIcon, "Pokeball-Icon.png"), self.previewimages),
        ]

        if "Left" in text:
            # Flip only necessary layers and reuse cache
            flipped_paths = self.flip_layers_y(layer, [0, 1])
            layer = [os.path.relpath(p, self.previewimages) for p in flipped_paths]

        elif "Right" in text:
            # Use original files for Right layout
            print("Restoring original right-side preview.")

        self.update_preview_layers(
            self.counterPreview,
            self.previewimages,
            layer,
            {
                0: self.mainColor,
                1: self.subColor,
                2: self.minMaxButtonColor,
                6: self.minMaxButtonColor,
                7: self.ballColor,
                8: self.ballOutline,
            },    
        )
        if "Vartiou" in text:
            layer = [*["Blank1.png"] * 3,os.path.relpath(os.path.join(self.custom_counter,self.customDrop.currentText(),"data/themes/default/res/counter-theme.png"), self.previewimages)]
            self.update_preview_layers(
            self.counterPreview,
            self.previewimages,
            layer,
            {
                0: self.mainColor,
                1: self.subColor,
                2: self.minMaxButtonColor,
                6: self.minMaxButtonColor,
                7: self.ballColor,
                8: self.ballOutline,
            },    
        )
            
    def flip_layers_y(self, image_paths: list, layers_to_flip: list = None):
        flipped_paths = []
        flipped_dir = os.path.join(self.previewimages, "Flipped")
        os.makedirs(flipped_dir, exist_ok=True)

        for idx, path in enumerate(image_paths):
            try:
                full_path = (
                    path
                    if os.path.isabs(path) or path.startswith(self.previewimages)
                    else os.path.join(self.previewimages, path)
                )

                # Only flip layers that need it
                if layers_to_flip and idx in layers_to_flip:
                    # Check cache first
                    if full_path in self.flipped_cache:
                        flipped_path = self.flipped_cache[full_path]
                    else:
                        img = Image.open(full_path).convert("RGBA")
                        img = img.transpose(Image.FLIP_LEFT_RIGHT)

                        # Save to flipped folder
                        flipped_path = os.path.join(flipped_dir, os.path.basename(full_path))
                        img.save(flipped_path)
                        self.flipped_cache[full_path] = flipped_path
                        print(f"Flipped and cached: {flipped_path}")

                    full_path = flipped_path

                flipped_paths.append(full_path)

            except Exception as e:
                print(f"⚠ Failed to process image {path}: {e}")
                flipped_paths.append(path)

        return flipped_paths

    def update_window_preview(self):
        self.update_preview_layers(
            self.windowPreview,
            self.previewimages,
            ["ButtonColor.png", "IconColor.png", "OtherColor.png",
            "SubColor.png", "AccentColor.png", "MainColor.png"],
            {
                0: self.buttonColorW,
                1: self.iconColorW,
                3: self.subColorW,
                4: self.accentColorW,
                5: self.mainColorW,
            },
            combine_map={2: (self.buttonColorW, self.subColorW)}
        )

    def update_hp_preview(self):
        self.update_preview_layers(
            self.hpBar,
            self.previewimages,
            ["HPBarBaseLayer.png", "HPBarSubColor.png", "HPBarText.png",
            "HPBarMax.png", "HPBarMid.png", "HPBarMin.png", "XPBar.png"],
            {
                1: self.subColorW,
                3: self.hpHighW,
                4: self.hpMidW,
                5: self.hpLowW,
                6: self.xpColorW,
            },
            combine_map={0: (self.buttonColorW, self.subColorW)}
        )

    def setup_color_hooks_for_preview(self, color_map, target_preview, by_name=False):
        for key, button in color_map.items():
            if by_name:
                button.colorChanged.connect(lambda c, name=key: target_preview.set_layer_color(name, QColor(c)))
            else:
                button.colorChanged.connect(lambda c, idx=key: target_preview.set_layer_tint(idx, QColor(c)))

    def setup_color_hooks(self):
        self.setup_color_hooks_for_preview({
            "reshiram-color": self.reshiramColor,
            "zekrom-color": self.zekromColor,
            "reshiram-aura": self.reshiramAura,
            "zekrom-aura": self.zekromAura,
        }, self.loginPreview, by_name=True)

        self.setup_color_hooks_for_preview({
            0: self.mainColor,
            1: self.subColor,
            2: self.minMaxButtonColor,
            7: self.ballColor,
            8: self.ballOutline,
        }, self.counterPreview)

        self.setup_color_hooks_for_preview({
            0: self.buttonColorW,
            1: self.iconColorW,
            3: self.subColorW,
            4: self.accentColorW,
            5: self.mainColorW,
        }, self.windowPreview)

        self.setup_color_hooks_for_preview({
            1: self.subColorW,
            3: self.hpHighW,
            4: self.hpMidW,
            5: self.hpLowW,
            6: self.xpColorW,
        }, self.hpBar)

    def combine_colors(self, color1: QColor, color2: QColor) -> QColor:
        r = (color1.red() + color2.red()) // 2
        g = (color1.green() + color2.green()) // 2
        b = (color1.blue() + color2.blue()) // 2
        a = (color1.alpha() + color2.alpha()) // 2
        return QColor(r, g, b, a)

    def updateFontColor(self, color, label):
        label.setStyleSheet(f"color: {color.name()};")

    def handle_zip_import(self, update_func, label_widget):
        file_path, _ = QFileDialog.getOpenFileName(None, "Select a Theme ZIP", "", "Zip Files (*.zip);;All Files (*)")
        if not file_path:
            return
        new_theme = self.theme_manager.add_theme_from_zip(file_path, parent_widget=self)
        if new_theme:
            update_func()
            label_widget.setText(f"✔ Imported: {os.path.basename(new_theme)}")
            label_widget.setStyleSheet("color: green; font-size: 9pt;")
        else:
            label_widget.setText("✖ Import failed. Please try again.")
            label_widget.setStyleSheet("color: red; font-size: 9pt;")

        QTimer.singleShot(30000, lambda: label_widget.setText(""))

    def handle_basic_import(self, update_func,target_dir, label_widget):
        file_path, _ = QFileDialog.getOpenFileName(None, "Select a Theme ZIP", "", "Zip Files (*.zip);;All Files (*)")
        if not file_path:
            return
        new_theme = self.theme_manager.unzip_file(file_path,target_dir, parent_widget=self)
        if new_theme:
            update_func()
            label_widget.setText(f"✔ Imported: {os.path.basename(new_theme)}")
            label_widget.setStyleSheet("color: green; font-size: 9pt;")
        else:
            label_widget.setText("✖ Import failed. Please try again.")
            label_widget.setStyleSheet("color: red; font-size: 9pt;")

        QTimer.singleShot(30000, lambda: label_widget.setText(""))    

    def handle_login_browse(self):
        self.handle_zip_import(self.update_login_drop, self.label_2_status)

    def handle_vartiou_browse(self):
        self.handle_basic_import(self.update_vartiou_drop,self.custom_counter, self.status_label_custom_counter)      

    def git_clone_or_pull(self, repo_url, destination, status_label):
        try:
            subprocess.run(["git", "--version"], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        except (subprocess.CalledProcessError, FileNotFoundError):
            status_label.setText("Git not found. Install Git and try again.")
            status_label.setStyleSheet("color: red; font-size: 18pt;")
            QTimer.singleShot(10000, lambda: status_label.setText(""))
            return

        try:
            # Check if destination exists and is a git repo
            if os.path.exists(destination) and os.path.exists(os.path.join(destination, ".git")):
                subprocess.run(["git", "-C", destination, "pull"], check=True)
                msg = "Updated"
            else:
                # If folder exists but not a git repo, delete it before cloning
                if os.path.exists(destination):
                    import shutil
                    shutil.rmtree(destination)
                subprocess.run(["git", "clone", repo_url, destination], check=True)
                msg = "Downloaded"
            
            status_label.setText(f"Archetype {msg}")
            status_label.setStyleSheet("color: green; font-size: 18pt;")
        except subprocess.CalledProcessError as e:
            status_label.setText(f"Failed!: {e}")
            status_label.setStyleSheet("color: red; font-size: 18pt;")

        QTimer.singleShot(30000, lambda: status_label.setText(""))
        self.get_Archstatus

    def downloadLatestArch(self):
        self.git_clone_or_pull("https://github.com/ssjshields/archetype", "Archetype", self.status_label_archetype)

    def make_label(self, parent, text="", font_size=12, bold=False, geometry=None, align=None):
        label = QtWidgets.QLabel(parent)
        if geometry:
            label.setGeometry(QtCore.QRect(*geometry))
        font = QtGui.QFont()
        font.setPointSize(font_size)
        font.setBold(bold)
        label.setFont(font)
        if align:
            label.setAlignment(align)
        label.setText(text)
        return label

    def save_config(self):
        # Load existing config if it exists
        if os.path.exists(self.configPath):
            try:
                with open(self.configPath, "r", encoding="utf-8") as f:
                    existing_config = json.load(f)
            except Exception as e:
                print(f"Failed to load existing config: {e}")
                existing_config = {}
        else:
            existing_config = {}

        # Preserve existing game path if it exists
        existing_game_path = existing_config.get("paths", {}).get("game_path")

        # Build new config
        config = {
            "colors": {
                "main-color": self.mainColorW.color().name(),
                "sub-color": self.subColorW.color().name(),
                "button-color": self.buttonColorW.color().name(),
                "accent-color": self.accentColorW.color().name(),
                "font-main-color": self.fontMainW.color().name(),
                "font-sub-color": self.fontSubW.color().name(),
                "font-button-color": self.fontButtonW.color().name(),
                "font-disabled-color": self.fontDisabledColorW.color().name(),
                "hp-high-color": self.hpHighW.color().name(),
                "hp-mid-color": self.hpMidW.color().name(),
                "hp-low-color": self.hpLowW.color().name(),
                "xp-color": self.xpColorW.color().name(),
                "friendship-color": self.friendshipColorW.color().name(),
                "icon-color": self.iconColorW.color().name(),
                "water-background": self.waterbg.color().name(),
                "water-warning": self.waterW.color().name(),
                "berry-progress": self.berryProgress.color().name(),
                "berry-progress-warning": self.berryWarning.color().name(),
                "berry-progress-disabled": self.berryDisabled.color().name(),
                "reshiram-color": self.reshiramColor.color().name(),
                "reshiram-aura": self.reshiramAura.color().name(),
                "zekrom-color": self.zekromColor.color().name(),
                "zekrom-aura": self.zekromAura.color().name(),
                "counter-ball-color": self.ballColor.color().name(),
                "counter-ball-outline":self.ballOutline.color().name(),
                "counter-min-max-button-color": self.minMaxButtonColor.color().name(),
                "counter-main-color": self.mainColor.color().name(),
                "counter-sub-color": self.subColor.color().name(),
                "counter-font-color": self.fontColor.color().name(),
                "counter-font-border":self.fontBorder.color().name(),
            },
            
            "paths": {
                "login_screen": self.loginDrop.currentText(),
                "encounter_counter": self.counterDrop.currentText(),
                "custom_counter_current": self.customDrop.currentText(),
                # Only use self.gamePath if there's no existing value
                "game_path": self.gamePath or existing_game_path,
            },

            "look":{
                "login_screen": os.path.join("assets/",self.loginDrop.currentText()),
                "arch_cursor": os.path.join("assets/",self.cursorDrop.currentText()),
                "arch_shape": os.path.join("assets/",self.iconDrop.currentText()),
                "speech_bubbles": os.path.join("assets/",self.speechDrop.currentText()),
            },
            "counter":{
                "encounter_counter":os.path.join("assets/",self.customDrop.currentText()),
            },

            "state": {
                "current_tab": self.tabWidget.currentIndex(),
                "loginDrop": self.loginDrop.currentIndex(),
                "counterDrop": self.counterDrop.currentIndex(),
                "customDrop": self.customDrop.currentIndex(),
                "bubblesDrop": self.speechDrop.currentIndex(),
                "icon_drop": self.iconDrop.currentIndex(),
                "cursor_drop": self.cursorDrop.currentIndex(),
            },
        }

        # Save
        with open(self.configPath, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=4)

        print(f"Config saved: {self.configPath}")

    def save_config_as(self):
        # Open a "Save As" dialog
        new_path, _ = QtWidgets.QFileDialog.getSaveFileName(
            None,
            "Save Configuration As",
            os.path.expanduser("~"),  # Start in home dir
            "JSON Files (*.json);;All Files (*)"
        )

        if not new_path:
            print("Save As canceled.")
            return

        # Ensure the path ends with .json
        if not new_path.lower().endswith(".json"):
            new_path += ".json"

        # Load existing config if possible
        if os.path.exists(self.configPath):
            try:
                with open(self.configPath, "r", encoding="utf-8") as f:
                    existing_config = json.load(f)
            except Exception as e:
                print(f"Failed to load existing config: {e}")
                existing_config = {}
        else:
            existing_config = {}

        # Preserve existing game path
        existing_game_path = existing_config.get("paths", {}).get("game_path")

        # Build config (same as save_config)
        config = {
            "colors": {
                "main-color": self.mainColorW.color().name(),
                "sub-color": self.subColorW.color().name(),
                "button-color": self.buttonColorW.color().name(),
                "accent-color": self.accentColorW.color().name(),
                "font-main-color": self.fontMainW.color().name(),
                "font-sub-color": self.fontSubW.color().name(),
                "font-button-color": self.fontButtonW.color().name(),
                "font-disabled-color": self.fontDisabledColorW.color().name(),
                "hp-high-color": self.hpHighW.color().name(),
                "hp-mid-color": self.hpMidW.color().name(),
                "hp-low-color": self.hpLowW.color().name(),
                "xp-color": self.xpColorW.color().name(),
                "friendship-color": self.friendshipColorW.color().name(),
                "icon-color": self.iconColorW.color().name(),
                "water-background": self.waterbg.color().name(),
                "water-warning": self.waterW.color().name(),
                "berry-progress": self.berryProgress.color().name(),
                "berry-progress-warning": self.berryWarning.color().name(),
                "berry-progress-disabled": self.berryDisabled.color().name(),
                "reshiram-color": self.reshiramColor.color().name(),
                "reshiram-aura": self.reshiramAura.color().name(),
                "zekrom-color": self.zekromColor.color().name(),
                "zekrom-aura": self.zekromAura.color().name(),
                "counter-ball-color": self.ballColor.color().name(),
                "counter-ball-outline":self.ballOutline.color().name(),
                "counter-min-max-button-color": self.minMaxButtonColor.color().name(),
                "counter-main-color": self.mainColor.color().name(),
                "counter-sub-color": self.subColor.color().name(),
                "counter-font-color": self.fontColor.color().name(),
                "counter-font-border":self.fontBorder.color().name(),
            },
            
            "paths": {
                "login_screen": self.loginDrop.currentText(),
                "encounter_counter": self.counterDrop.currentText(),
                "custom_counter_current": self.customDrop.currentText(),
                # Only use self.gamePath if there's no existing value
                "game_path": self.gamePath or existing_game_path,
            },

            "look":{
                "login_screen": os.path.join("assets/",self.loginDrop.currentText()),
                "arch_cursor": os.path.join("assets/",self.cursorDrop.currentText()),
                "arch_shape": os.path.join("assets/",self.iconDrop.currentText()),
                "speech_bubbles": os.path.join("assets/",self.speechDrop.currentText()),
            },
            "counter":{
                "encounter_counter":os.path.join("assets/",self.customDrop.currentText()),
            },

            "state": {
                "current_tab": self.tabWidget.currentIndex(),
                "loginDrop": self.loginDrop.currentIndex(),
                "counterDrop": self.counterDrop.currentIndex(),
                "customDrop": self.customDrop.currentIndex(),
                "bubblesDrop": self.speechDrop.currentIndex(),
                "icon_drop": self.iconDrop.currentIndex(),
                "cursor_drop": self.cursorDrop.currentIndex(),
            },
        }

        # Write out the new file
        try:
            with open(new_path, "w", encoding="utf-8") as f:
                json.dump(config, f, indent=4)
            print(f"Config saved as: {new_path}")
            # Optionally update self.configPath to new one:
            self.configPath = new_path
        except Exception as e:
            print(f"Failed to save config as {new_path}: {e}")

    def get_Archstatus(self):
        repo_path = self.archetype_root
        if not os.path.isdir(repo_path):
            return '<span style="color: gray;">Path does not exist</span>'

        git_dir = os.path.join(repo_path, ".git")
        if not os.path.isdir(git_dir):
            return '<span style="color: orange;">Not a git repository</span>'

        try:
            subprocess.run(
                ["git", "fetch"],
                cwd=repo_path,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )

            result = subprocess.run(
                ["git", "status", "-uno"],
                cwd=repo_path,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )

            output = result.stdout.lower()
            if "up to date" in output or "ahead of" in output:
                return '<span style="color: green;">Up to date</span>'
            elif "behind" in output:
                return '<span style="color: red;">Updates available</span>'
            else:
                return '<span style="color: blue;">Status unclear</span>'
        except subprocess.CalledProcessError as e:
            print(f"Git command failed: {e}")
            return '<span style="color: red;">Git error</span>'

    def _load_config_from_path(self, path): 
        if not os.path.exists(path):
            print(f"No config file found at {path}, using defaults.") 
            return 

        with open(path, "r", encoding="utf-8") as f:
            config = json.load(f)

        # Restore colors
        for key, value in config.get("colors", {}).items(): 
            widget = getattr(self, key, None) 
            if widget: 
                widget.setColor(QtGui.QColor(value)) 

        # Restore paths 
        # paths = config.get("paths", {}) 
        # self.custom_login = paths.get("custom_login", self.custom_login) 
        # # self.custom_counter = paths.get("custom_counter", self.custom_counter) 
        # self.previewimages = paths.get("previewimages", self.previewimages)

        # Restore state (tabs, combo boxes, etc.)
        state = config.get("state", {})

        if hasattr(self, "tabWidget") and isinstance(self.tabWidget, QtWidgets.QTabWidget):
            self.tabWidget.setCurrentIndex(state.get("current_tab", 0))

        if hasattr(self, "loginDrop") and isinstance(self.loginDrop, QtWidgets.QComboBox):
            self.loginDrop.setCurrentIndex(state.get("loginDrop", 0))

        if hasattr(self, "counterDrop") and isinstance(self.counterDrop, QtWidgets.QComboBox):
            self.counterDrop.setCurrentIndex(state.get("counterDrop", 0))

        if hasattr(self, "customDrop") and isinstance(self.customDrop, QtWidgets.QComboBox):
            self.customDrop.setCurrentIndex(state.get("customDrop", 0))

        if hasattr(self, "bubblesDrop") and isinstance(self.bubblesDrop, QtWidgets.QComboBox):
            self.bubblesDrop.setCurrentIndex(state.get("bubblesDrop", 0))

        if hasattr(self, "iconDrop") and isinstance(self.iconDrop, QtWidgets.QComboBox):
            self.iconDrop.setCurrentIndex(state.get("icon_drop", 0))
            
        if hasattr(self, "cursorDrop") and isinstance(self.cursorDrop, QtWidgets.QComboBox):
            self.cursorDrop.setCurrentIndex(state.get("cursor_drop", 0))

    def load_last_config(self):
        """Load last used config file."""
        self._load_config_from_path(self.configPath)

    def load_default_config(self):
        """Load default config file."""
        self._load_config_from_path(self.defaultConfig)

    def load_config(self):
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            None,  # <- no parent, works in all cases
            "Select Config File",
            os.path.dirname(self.configPath) if hasattr(self, "configPath") else "",
            "JSON Files (*.json);;All Files (*)"
        )

        # If user cancels
        if not file_path:
            print("No config file selected, using defaults.")
            return

        if not os.path.exists(file_path):
            print(f"Selected file does not exist: {file_path}")
            return

        # Use the shared loader
        self._load_config_from_path(file_path)

        # Update internal config path to the chosen one
        self.configPath = file_path

        print(f"Loaded config from: {file_path}")

    def get_current_path(self, config_file=None):
            config_file = config_file or getattr(self, "configPath", None)
            if not config_file or not os.path.isfile(config_file):
                print("Config file not found.")
                return None

            try:
                with open(config_file, "r", encoding="utf-8") as f:
                    config = json.load(f)
                paths = config.get("paths", {})
                return paths.get("game_path", None)
            except Exception as e:
                print(f"Failed to read config: {e}")
                return None

    def select_file_path(self):
        dialog = QtWidgets.QFileDialog()
        dialog.setWindowTitle("Select Pokemmo Installation Location")
        dialog.setFileMode(QtWidgets.QFileDialog.Directory)
        dialog.setFilter(QDir.AllEntries | QDir.Hidden) 
        dialog.setOption(QtWidgets.QFileDialog.ShowDirsOnly, False)

        if dialog.exec_():
            selected_files = dialog.selectedFiles()
            if selected_files:
                self.gamePath = selected_files[0]
                self.status_label_archetype.setText(f"Game path set to {self.gamePath}")
                self.status_label_archetype.setStyleSheet("color: green; font-size: 18pt;")
                self.save_config()  # save it immediately to config (if you want)

    def complete_build(self):
        self.save_config
        colors = CompleteBuild(self.configPath,os.path.join(self.themeFolder,"CHOOSE_YOUR_COLORS.xml"))
        counter = CompleteBuild(self.configPath,os.path.join(self.themeFolder,"CHOOSE_YOUR_COUNTER.xml"))
        look = CompleteBuild(self.configPath,os.path.join(self.themeFolder,"CHOOSE_YOUR_LOOK.xml"))

        colors.generate_xml()
        counter.generate_xml()
        look.generate_xml()

        if self.loginDrop.currentText() != "Unova.xml" or "Allstars.xml":
            self.copy_files(os.path.join("./CustomThemes",self.loginDrop.currentText().removesuffix(".xml")) ,self.assets_dir)

        if self.customDrop.currentIndex() == "Counter-Vartiou.xml":
            self.copy_files(os.path.join("./CustomCounters",self.customDrop.currentText()) ,self.assets_dir)

        self.gamePath = self.get_current_path(self.configPath)
        print(f"current path is: {self.gamePath}")
        self.compress_move("./Archetype", os.path.join(self.gamePath,"data/mods/"),"Arch")

    def compress_move(self, source_folder: str, destination_dir: str, zip_name: str = None):
        import os, shutil, zipfile

        if not os.path.isdir(source_folder):
            raise FileNotFoundError(f"Source folder not found: {source_folder}")

        os.makedirs(destination_dir, exist_ok=True)

        if not zip_name:
            zip_name = os.path.basename(os.path.normpath(source_folder))

        zip_path = os.path.join(destination_dir, f"{zip_name}.zip")
        temp_zip = f"{zip_name}.zip"

        with zipfile.ZipFile(temp_zip, "w", zipfile.ZIP_DEFLATED) as zipf:
            for root, _, files in os.walk(source_folder):
                for file in files:
                    file_path = os.path.join(root, file)
                    arcname = os.path.relpath(file_path, source_folder)
                    zipf.write(file_path, arcname)

        shutil.move(temp_zip, zip_path)
        print(f"'{source_folder}' compressed and moved to '{zip_path}'")

        return zip_path

    def copy_files(self,src_folder, dst_folder):
        if not os.path.exists(src_folder):
            print(f"Source folder does not exist: {src_folder}")
            return

        if not os.path.exists(dst_folder):
            os.makedirs(dst_folder)
        
        for item in os.listdir(src_folder):
            src_path = os.path.join(src_folder, item)
            dst_path = os.path.join(dst_folder, item)
            
            if os.path.isdir(src_path):
                # Recursively copy entire subfolder
                shutil.copytree(src_path, dst_path, dirs_exist_ok=True)
            else:
                # Copy single file
                shutil.copy2(src_path, dst_path)
        
        print(f"Contents copied from '{src_folder}' to '{dst_folder}'")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archetype Manager"))
        self.label_8.setText(_translate("MainWindow", "reshiram color\n"
        "\n"
        "reshiram aura\n"
        "\n"
        "zekrom color\n"
        "\n"
        "zekrom aura"))
        self.label_9.setText(_translate("MainWindow", "Unova Login Screen Options"))
        self.label_2.setText(_translate("MainWindow", "Add Your Own Login Screen"))
        self.loginBrowse.setText(_translate("MainWindow", "Browse..."))
        self.label.setText(_translate("MainWindow", "Choose Login Screen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LoginScreen), _translate("MainWindow", "Login Screen"))
        self.label_6.setText(_translate("MainWindow", "Encounter Counter Colors"))
        self.label_7.setText(_translate("MainWindow", " ball color\n"
        "\n"
        " ball outline\n"
        "\n"
        " min max button color\n"
        "\n"
        " main color\n"
        "\n"
        " sub color\n"
        "\n"
        " font\n"
        "\n"
        " font border"))
        self.label_5.setText(_translate("MainWindow", "Encounter Counter"))
        self.label_3.setText(_translate("MainWindow", " Add Vartiou here"))
        self.varitouBrowse.setText(_translate("MainWindow", "Browse..."))
        self.label_16.setText(_translate("MainWindow", "This will do the work getting what is needed, just choose the zip file"))
        self.label_18.setText(_translate("MainWindow", "Choose Custom"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EncounterCounter), _translate("MainWindow", "Encounter Counter"))
        self.label_11.setText(_translate("MainWindow", "hp high \n"
        "hp mid\n"
        "hp low\n"
        "xp\n"
        "friendship"))
        self.label_10.setText(_translate("MainWindow", "main\n"
        "sub\n"
        "button\n"
        "accent"))
        self.label_4.setText(_translate("MainWindow", "font main\n"
        "font sub\n"
        "font button\n"
        "font disabled\nIcon"))
        self.label_13.setText(_translate("MainWindow", "Main Window"))
        # self.label_12.setText(_translate("MainWindow", "main \n\nsub\n\nbutton\n\naccent\n\nIcon"))

        self.counterText.setText(_translate("MainWindow","Pokemon        1\n\n\nPokemon        2\n\n\nPokemon        3"))
        self.windowTextFontMain.setText(_translate("MainWindow","           Global Trade Link"))
        self.windowTextFontMain2.setText(_translate("MainWindow","Pokemon Listings"))
        self.windowTextFontSub.setText(_translate("MainWindow"," Modest     20               11     16     23               $5,000                   Just now            28 days                      Buy"))
        self.windowTextFontSub2.setText(_translate("MainWindow","Pokemon\t           Nature\t\tIVs\t\t            Price\t     Start Date          End Date\tBuy"))
        self.windowTextFontMinIV.setText(_translate("MainWindow","0"))
        self.windowTextFontMaxIV.setText(_translate("MainWindow","31"))
        self.windowTextFontButton1.setText(_translate("MainWindow","Item Market       Item Listings       Your Listings       Create Listing       Trade Log"))
        self.windowTextFontButton2.setText(_translate("MainWindow","Select Template\t\t\t\t\t\t\t          Advanced Search             ↻               Newest"))
        self.windowTextFontButton3.setText(_translate("MainWindow","Lv. 36 Evee"))
        self.windowTextFontButton4.setText(_translate("MainWindow","2         3         4         5         6         7         8         9        10       11       12      13       14       >>"))
        self.windowTextFontDisabled1.setText(_translate("MainWindow","☒"))
        self.windowTextFontDisabled2.setText(_translate("MainWindow","<<      1"))
        self.label_14.setText(_translate("MainWindow", "Berry Watering Colors"))
        self.label_12.setText(_translate("MainWindow", "waterBG\nwaterwarning\nberryprogress\nberrywarning\nberrydisabled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WindowColors), _translate("MainWindow", "Window Colors"))
        self.label_15.setText(_translate("MainWindow", "Cursor Type"))
        self.cursorBrowse.setText(_translate("MainWindow", "Browse..."))
        self.label_17.setText(_translate("MainWindow", "Add Custom Cursor"))
        # self.iconDrop.setItemText(0, _translate("MainWindow", "Round"))
        # self.iconDrop.setItemText(1, _translate("MainWindow", "Sharp"))
        self.label_20.setText(_translate("MainWindow", "Icon Type"))
        self.label_23.setText(_translate("MainWindow", "Speech Bubbles"))
        self.speechBrowse.setText(_translate("MainWindow", "Browse..."))
        self.label_24.setText(_translate("MainWindow", "Add Custom Speech Bubbles"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OtherScreen), _translate("MainWindow", "Other"))
        self.label_25.setText(_translate("MainWindow", "Get/Update Archetype"))
        self.downloadArch.setText(_translate("MainWindow", "Download"))

        self.setGamePath.setText(_translate("MainWindow", "Browse"))
        # self.loadConfig.setText(_translate("MainWindow", "Load"))
        # self.label_27.setText(_translate("MainWindow", "Load Default Config"))
        self.completeMod.setText(_translate("MainWindow", "Complete"))
        self.label_28.setText(_translate("MainWindow", "Finish and add to Pokemmo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Archetype), _translate("MainWindow", "Archetype"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Mods), _translate("MainWindow", "Mods"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSaveAs.setText(_translate("MainWindow","Save As..."))
        self.actionLoadDefault.setText(_translate("MainWindow", "Load Defaults"))


from colorButton import ColorButton as KColorButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
